services:
  - type: web
    name: digital-library-portal
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn --pythonpath . libraryproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: WEB_CONCURRENCY
        value: "2"
